version: "3.0"
# named volumes
volumes:
  redis-vol:
services:
      # Esto es un mapa 
  anyApp:
    build:
      context: src/${PROJECT_LANG:-python}
    entrypoint: ["sh", "-c", "pip install -r requirements.txt && python app.py"]
    image: ${DOCKER_REPO:-vermunoz}/${PROJECT_LANG:-python}-expert:v1.0
    environment:
    # Esta es una Lista (se distingue por los guiones)
      - FOO=bar
      - VAR=var
      - REDIS_HOST=db
    # Activa el modo Tini 
    #init: true
    ports:
      - 8080:8080
    working_dir: /code/
    volumes:
      - ./src/${PROJECT_LANG:-python}:/code
# # FQDN == fully qualified domain name
  db:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-vol:/data
    
#  apacheApp:
#      context: src/${PROJECT:-apache} 
#    image: ${DOCKER_REPO:-vermunoz}/${PROJECT}-expert:v1.0
#    init: true 
#    ports: 
#     - 80:80
    
