apiVersion: v1 
kind: Pod
metadata: 
  name: static-web
  labels: 
    role: myrole
# Specification 
spec: 
  containers: 
    - name: web
      image: httpd
      ports: 
        - name: web 
          containerPort: 80 
          protocol: TCP 
    - name: mysql
      image: mysql
      ports: 
        - name: web 
          containerPort: 3306
          protocol: TCP 
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword  
    - name: whomai
      image: jwilder/whoami
      ports: 
       - name: web 
         containerPort: 8000
         protocol: TCP 

