apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-ecr
  namespace: kube-system
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: QUtJQVkzMzRUNUpFREtJWUtIRU0=
  AWS_SECRET_ACCESS_KEY: bFBzQlk5V1hSNmpVNkp2SjM0RTQ3SXpHRWhmejFQYmk0MEw3QldWRQ==
  aws-account: NjA5NjA5ODM3MTI4
  aws-region: dXMtd2VzdC0y
type: Opaque