apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: backend-with-yaml
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://192.168.64.3:8443
  project: default
  source:
    path: kubernetes/gitops/back-app
    repoURL: https://github.com/VerMunoz/container-expert-scratch.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false